# Generated by Django 4.2.8 on 2023-12-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
